title: My Blog
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog.
baseurl: "" # the subpath of your site, e.g. /blog, if applicable
url: "https://yili2325.github.io" # the base hostname & protocol for your site
markdown: kramdown
